server:
  port: 8081


spring:
  profiles:
    active: dev
  application:
    name: aplicacao-segura
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: of-pagamentos
            authorization-grant-type: client_credentials
            client-authentication-method: private_key_jwt
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/master
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master

app:
  security:
    resource-server:
      expected-audience: http://localhost:8080/realms/master
logging:
  level:
    root: info
