services:
  postgres:
    image: postgres:17
    container_name: certification-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: certification
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: certification-keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "false"
      KC_CACHE: local
    command:
      - start-dev
      - --import-realm
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:192.168.0.83"
    # volumes:
      # - ./.keycloak/realm-exports/default.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - default_network
      # O bloco abaixo CORRIGE o erro relatado
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9000 && printf \"GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n\" >&3 && cat <&3 | grep -q \"200 OK\"'"]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 20s # Aumentado caso o banco demore para iniciar
  servico-a:
    build:
      context: ../Java/servico-a
      dockerfile: Dockerfile-servico
    container_name: servico-a
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "8085:8080"
    volumes:
      - ../Java/servico-a/target:/app/target:ro
    networks:
      - default_network
  api-b:
    build:
      context: ../Java/api-b
      dockerfile: Dockerfile-api
    container_name: api-b
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "8086:8080"
    volumes:
      - ../Java/api-b/target:/app/target:ro
    networks:
       - default_network

networks:
  default_network:
    driver: bridge

volumes:
  postgres_data:
 
